<?php
/**
 * Head & Footer Code plugin for WordPress
 *
 * @link        https://webkp.in/
 * @since       1.0.0
 * @package     Head_Footer_Code
 *
 * Plugin Name: Head & Footer Script
 * Plugin URI:  #
 * Description: Easy add site-wide, category or article specific custom code before the closing <strong>&lt;/head&gt;</strong> and <strong>&lt;/body&gt;</strong> or after opening <strong>&lt;body&gt;</strong> HTML tag.
 * Version:     1.3.0
 * Author:      Kaushik Parmar
 * Author URI:  https://webkp.in/
 * License:     GPLv3
 * License URI: https://webkp.in/licenses/gpl-3.0.txt
 * Text Domain: head-footer-script
 * Domain Path: /languages
 * Requires at elast: 1.0
 * Tested up to: 6.0
 * Requires PHP: 5.6
 */





/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class Headerfooter {
	private $headerfooter_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'headerfooter_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'headerfooter_page_init' ) );
	}

	public function headerfooter_add_plugin_page() {
		add_menu_page(
			'Header Footer Scripts', // page_title
			'Header Footer Scripts', // menu_title
			'manage_options', // capability
			'headerfooter', // menu_slug
			array( $this, 'headerfooter_create_admin_page' ), // function
			'dashicons-admin-tools', // icon_url
			2 // position
		);
	}

	public function headerfooter_create_admin_page() {
		$this->headerfooter_options = get_option( 'headerfooter_option_name' ); ?>

		<div class="wrap">
			<h2>Header Footer Scripts</h2>
			<p>Put your header and footer codes</p>
			<?php
		$headerfooter_options = get_option( 'headerfooter_option_name' );
		echo $headerfooter_options['header_0'];
		settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'headerfooter_option_group' );
					do_settings_sections( 'headerfooter-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function headerfooter_page_init() {
		register_setting(
			'headerfooter_option_group', // option_group
			'headerfooter_option_name', // option_name
			array( $this, 'headerfooter_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'headerfooter_setting_section', // id
			'Settings', // title
			array( $this, 'headerfooter_section_info' ), // callback
			'headerfooter-admin' // page
		);

		add_settings_field(
			'header_0', // id
			'Header', // title
			array( $this, 'header_0_callback' ), // callback
			'headerfooter-admin', // page
			'headerfooter_setting_section' // section
		);

		add_settings_field(
			'footer_1', // id
			'Footer', // title
			array( $this, 'footer_1_callback' ), // callback
			'headerfooter-admin', // page
			'headerfooter_setting_section' // section
		);
	}

	public function headerfooter_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['header_0'] ) ) {
			$sanitary_values['header_0'] = esc_textarea( $input['header_0'] );
		}

		if ( isset( $input['footer_1'] ) ) {
			$sanitary_values['footer_1'] = esc_textarea( $input['footer_1'] );
		}

		return $sanitary_values;
	}

	public function headerfooter_section_info() {
		
	}

	public function header_0_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="headerfooter_option_name[header_0]" id="header_0">%s</textarea>',
			isset( $this->headerfooter_options['header_0'] ) ? esc_attr( $this->headerfooter_options['header_0']) : ''
		);
	}

	public function footer_1_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="headerfooter_option_name[footer_1]" id="footer_1">%s</textarea>',
			isset( $this->headerfooter_options['footer_1'] ) ? esc_attr( $this->headerfooter_options['footer_1']) : ''
		);
	}

}
if ( is_admin() )
	$headerfooter = new Headerfooter();

/* 
 * Retrieve this value with:
 * $headerfooter_options = get_option( 'headerfooter_option_name' ); // Array of All Options
 * $header_0 = $headerfooter_options['header_0']; // Header
 * $footer_1 = $headerfooter_options['footer_1']; // Footer
 */

//$header_0 = htmlspecialchars_decode($headerfooter_options['header_0']);
function hedaerscript(){
	$headerfooter_options = get_option( 'headerfooter_option_name' );
	echo htmlspecialchars_decode($headerfooter_options['header_0']);
}
add_action('wp_head','hedaerscript');

function footerscript(){
	$headerfooter_options = get_option( 'headerfooter_option_name' );
	echo htmlspecialchars_decode($headerfooter_options['footer_1']);
}
add_action('wp_head','footerscript');
?>